name: TESTS

 
on:

  push:
    branches: [ main ]


  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: npm install

      - name: verify
        run: ./node_modules/.bin/cypress verify
        run: ./node_modules/.bin/cypress info
        
      - name: test
        run: ./node_modules/.bin/cypress run --record --key ${{ secrets.CYPRESS_DASHBOARD_KEY }}
